version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: bot_database
      MYSQL_ROOT_PASSWORD: root


  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1


  bot_tg:
    image: python:3.11.4
    restart: always
    build: ./
